use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'

target 'Anvil_Example' do
  pod 'Anvil', :path => '../'

  target 'Anvil_Tests' do
    inherit! :search_paths

    
  end
end
